import { Blueprint } from "./inventoryItems/Blueprint";
import { HarvestedItem } from "./inventoryItems/HarvestedItem";
import { Seed } from "./inventoryItems/Seed";
import { Decoration } from "./placedItems/Decoration";
import { EmptyItem } from "./placedItems/EmptyItem";
import { Plant } from "./placedItems/Plant";
import { BlueprintTemplate } from "./templates/models/InventoryItemTemplates/BlueprintTemplate";
import { itemTemplateFactory } from "./templates/models/ItemTemplateFactory";
import { PlantTemplate } from "./templates/models/PlacedItemTemplates/PlantTemplate";
import { SeedTemplate } from "./templates/models/InventoryItemTemplates/SeedTemplate";
import { v4 as uuidv4 } from 'uuid';
import { HarvestedItemTemplate } from "./templates/models/InventoryItemTemplates/HarvestedItemTemplate";
import { DecorationTemplate } from "./templates/models/PlacedItemTemplates/DecorationTemplate";
import { EmptyItemTemplate } from "./templates/models/PlacedItemTemplates/EmptyItemTemplate";
import Shovel from "./tools/Shovel";
import { ShovelTemplate } from "./templates/models/ToolTemplates/ShovelTemplate";
import { PlacedEggTemplate } from "./templates/models/PlacedItemTemplates/PlacedEggTemplate";
import { PlacedEgg } from "./placedItems/PlacedEgg";

export const generateRandomPlacedItem = () => {
	const placedItems = Object.values(itemTemplateFactory.repository.PlacedItems).flat().filter(item => item.name != "error");
	return generatePlacedItem(placedItems[Math.floor(Math.random() * placedItems.length)].name, "autogenerated");
}

export const generateRandomInventoryItem = () => {
	const inventoryItems = Object.values(itemTemplateFactory.repository.InventoryItems).flat().filter(item => item.name != "error");
	return generateInventoryItem(inventoryItems[Math.floor(Math.random() * inventoryItems.length)].name, 1);
}


/**
 * @itemName the item name ie. apple
 * @status the status string
 */
export const generatePlacedItem = (itemName: string, status: string) => {
	const itemData = itemTemplateFactory.getPlacedItemTemplateByName(itemName);
	if (!itemData) return new EmptyItem(uuidv4(), EmptyItemTemplate.getErrorTemplate(), '');
	switch (itemData.subtype) {
		case "Plant":
			//TODO: Replace type assertion with type guard
			//But this is placeholder stuff so dont worry about it too much
			const plantItemData = itemData as PlantTemplate;
			return new Plant(uuidv4(), plantItemData, status);
		case "Decoration":
			const decorationItemData = itemData as DecorationTemplate;
			return new Decoration(uuidv4(), decorationItemData, status);
		case "Ground":
			const emptyItemData = itemData as EmptyItemTemplate;
			return new EmptyItem(uuidv4(), emptyItemData, status);
		default:
			console.log('Could not find item, generating error item.');
			return new EmptyItem(uuidv4(), EmptyItemTemplate.getErrorTemplate(), '');
	}
}

/**
 * @itemName the item name, ie. apple seed
 * @quantity the quantity
 */
export const generateInventoryItem = (itemName: string, quantity: number) => {
	const itemData = itemTemplateFactory.getInventoryItemTemplateByName(itemName);
	
	if (!itemData){ 
		console.log(`generating failed item ${itemName}`);
		return new Seed(uuidv4(), SeedTemplate.getErrorTemplate(), 1);
	}
	switch (itemData.subtype) {
		case "Seed":
			//TODO: Replace type assertion with type guard
			//But this is placeholder stuff so dont worry about it too much
			const seedItemData = itemData as SeedTemplate;
			return new Seed(uuidv4(), seedItemData, quantity);
		case "Blueprint":
			const blueprintItemData = itemData as BlueprintTemplate;
			return new Blueprint(uuidv4(), blueprintItemData, quantity);
		case "HarvestedItem":
			const harvestedItemData = itemData as HarvestedItemTemplate;
			return new HarvestedItem(uuidv4(), harvestedItemData, quantity);
		default:
			console.log(`Could not find item ${itemName}, generating error item.`);
			return new Seed(uuidv4(), SeedTemplate.getErrorTemplate(), 1);
	}
}

/**
 * @toolName the tool name, ie. basic shovel
 * @quantity the quantity
 */
 export const generateTool = (toolName: string) => {
	const itemData = itemTemplateFactory.getToolTemplateByName(toolName);
	if (!itemData) return new Shovel(uuidv4(), ShovelTemplate.getErrorTemplate());
	switch (itemData.type) {
		case "Shovel":
			//TODO: Replace type assertion with type guard
			const shovelItemData = itemData as ShovelTemplate;
			return new Shovel(uuidv4(), shovelItemData);
		default:
			console.log(`Could not find item ${toolName}, generating error item.`);
			return new Shovel(uuidv4(), ShovelTemplate.getErrorTemplate());
	}
}