import { Blueprint } from "./inventoryItems/Blueprint";
import { HarvestedItem } from "./inventoryItems/HarvestedItem";
import { Seed } from "./inventoryItems/Seed";
import { Decoration } from "./placedItems/Decoration";
import { EmptyItem } from "./placedItems/EmptyItem";
import { Plant } from "./placedItems/Plant";
import { BlueprintTemplate } from "./templates/models/BlueprintTemplate";
import { DecorationTemplate } from "./templates/models/DecorationTemplate";
import { EmptyItemTemplate } from "./templates/models/EmptyItemTemplate";
import { HarvestedItemTemplate } from "./templates/models/HarvestedItemTemplate";
import { placeholderItemTemplates } from "./templates/models/PlaceholderItemTemplate";
import { PlantTemplate } from "./templates/models/PlantTemplate";
import { SeedTemplate } from "./templates/models/SeedTemplate";
import { v4 as uuidv4 } from 'uuid';

export const generateRandomPlaceholderPlacedItem = () => {
	const placedItems = Object.values(placeholderItemTemplates.repository.PlacedItems).flat().filter(item => item.name != "error");
	return generateNewPlaceholderPlacedItem(placedItems[Math.floor(Math.random() * placedItems.length)].name, "autogenerated");
}

export const generateRandomPlaceholderInventoryItem = () => {
	const inventoryItems = Object.values(placeholderItemTemplates.repository.InventoryItems).flat().filter(item => item.name != "error");
	return generateNewPlaceholderInventoryItem(inventoryItems[Math.floor(Math.random() * inventoryItems.length)].name, 1);
}


/**
 * @itemName the item name ie. apple
 * @status the status string
 */
export const generateNewPlaceholderPlacedItem = (itemName: string, status: string) => {
	const itemData = placeholderItemTemplates.getPlacedItemTemplateByName(itemName);
	if (!itemData) return new EmptyItem(uuidv4(), EmptyItemTemplate.getErrorTemplate(), '');
	switch (itemData.subtype) {
		case "Plant":
			//TODO: Replace type assertion with type guard
			//But this is placeholder stuff so dont worry about it too much
			const plantItemData = itemData as PlantTemplate;
			return new Plant(uuidv4(), plantItemData, status);
		case "Decoration":
			const decorationItemData = itemData as DecorationTemplate;
			return new Decoration(uuidv4(), decorationItemData, status);
		case "Ground":
			const emptyItemData = itemData as EmptyItemTemplate;
			return new EmptyItem(uuidv4(), emptyItemData, status);
		default:
			console.log('Could not find item, generating error item.');
			return new EmptyItem(uuidv4(), EmptyItemTemplate.getErrorTemplate(), '');
	}
}

/**
 * @itemName the item name, ie. apple seed
 * @quantity the quantity
 */
export const generateNewPlaceholderInventoryItem = (itemName: string, quantity: number) => {
	const itemData = placeholderItemTemplates.getInventoryItemTemplateByName(itemName);
	if (!itemData) return new Seed(uuidv4(), SeedTemplate.getErrorTemplate(), 1);
	switch (itemData.subtype) {
		case "Seed":
			//TODO: Replace type assertion with type guard
			//But this is placeholder stuff so dont worry about it too much
			const seedItemData = itemData as SeedTemplate;
			return new Seed(uuidv4(), seedItemData, quantity);
		case "Blueprint":
			const blueprintItemData = itemData as BlueprintTemplate;
			return new Blueprint(uuidv4(), blueprintItemData, quantity);
		case "HarvestedItem":
			const harvestedItemData = itemData as HarvestedItemTemplate;
			return new HarvestedItem(uuidv4(), harvestedItemData, quantity);
		default:
			console.log(`Could not find item ${itemName}, generating error item.`);
			return new Seed(uuidv4(), SeedTemplate.getErrorTemplate(), 1);
	}
}
