import { StoreProvider } from "@/components/contextProviders/StoreProvider";
import Layout from "@/components/layout";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Layout>
            {children}
          </Layout>
        </StoreProvider>
        </body>
    </html>
  );
}
