AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 128
    Timeout: 5
    Environment:
      Variables:
        DB_HOST: !Ref DBEndpoint
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_NAME: !Ref DBName
        DB_PORT: "5432"
        REGION: !Ref AWS::Region
    VpcConfig:
      SecurityGroupIds:
        - !Ref ExistingSecurityGroup1Id
        - !Ref ExistingSecurityGroup2Id
      SubnetIds:
        - !Ref ExistingSubnetA
        - !Ref ExistingSubnetB

Resources:
  SelectFromDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: selectFromDB/app.handler
      Role: !Ref LambdaExecutionRoleArn
      FunctionName: garden-select

  InsertDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: insertDB/app.handler
      Role: !Ref LambdaExecutionRoleArn
      FunctionName: garden-insert

  UpdateDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: updateDB/app.handler
      Role: !Ref LambdaExecutionRoleArn
      FunctionName: garden-update

  DeleteDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deleteDB/app.handler
      Role: !Ref LambdaExecutionRoleArn
      FunctionName: garden-delete

Parameters:
  DBEndpoint:
    Type: String
    Description: "The existing RDS endpoint (e.g., my-database.xxxxx.region.rds.amazonaws.com)"
  DBUser:
    Type: String
    Description: "The RDS database username"
  DBPassword:
    Type: String
    Description: "The RDS database password"
  DBName:
    Type: String
    Description: "The name of the RDS database"
  ExistingSecurityGroup1Id:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Existing security group ID for RDS -> Lambda"
  ExistingSecurityGroup2Id:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Existing security group ID for Lambda -> RDS"
  ExistingSubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: "First existing subnet ID"
  ExistingSubnetB:
    Type: AWS::EC2::Subnet::Id
    Description: "Second existing subnet ID"
  LambdaExecutionRoleArn:
    Type: String
    Description: "The ARN of the Lambda execution role"
